//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyVersion("1.0.0.0")]
[assembly: System.Windows.Forms.AxHost.TypeLibraryTimeStamp("08/17/2010 16:44:18")]

namespace AxDPFPCtlXLib {
    
    
    [System.Windows.Forms.AxHost.ClsidAttribute("{f4ad5526-3497-4b8c-873a-a108ea777493}")]
    [System.ComponentModel.DesignTimeVisibleAttribute(true)]
    [System.ComponentModel.DefaultEvent("OnComplete")]
    public class AxDPFPVerificationControl : System.Windows.Forms.AxHost {
        
        private DPFPCtlXLib.IDPFPVerificationControl ocx;
        
        private AxDPFPVerificationControlEventMulticaster eventMulticaster;
        
        private System.Windows.Forms.AxHost.ConnectionPointCookie cookie;
        
        public AxDPFPVerificationControl() : 
                base("f4ad5526-3497-4b8c-873a-a108ea777493") {
        }
        
        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        [System.Runtime.InteropServices.DispIdAttribute(1)]
        public virtual string ReaderSerialNumber {
            get {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("ReaderSerialNumber", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertyGet);
                }
                return this.ocx.ReaderSerialNumber;
            }
            set {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("ReaderSerialNumber", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertySet);
                }
                this.ocx.ReaderSerialNumber = value;
            }
        }
        
        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        [System.Runtime.InteropServices.DispIdAttribute(2)]
        public virtual bool Active {
            get {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("Active", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertyGet);
                }
                return this.ocx.Active;
            }
            set {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("Active", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertySet);
                }
                this.ocx.Active = value;
            }
        }
        
        public event _IDPFPVerificationControlEvents_OnCompleteEventHandler OnComplete;
        
        protected override void CreateSink() {
            try {
                this.eventMulticaster = new AxDPFPVerificationControlEventMulticaster(this);
                this.cookie = new System.Windows.Forms.AxHost.ConnectionPointCookie(this.ocx, this.eventMulticaster, typeof(DPFPCtlXLib._IDPFPVerificationControlEvents));
            }
            catch (System.Exception ) {
            }
        }
        
        protected override void DetachSink() {
            try {
                this.cookie.Disconnect();
            }
            catch (System.Exception ) {
            }
        }
        
        protected override void AttachInterfaces() {
            try {
                this.ocx = ((DPFPCtlXLib.IDPFPVerificationControl)(this.GetOcx()));
            }
            catch (System.Exception ) {
            }
        }
        
        internal void RaiseOnOnComplete(object sender, _IDPFPVerificationControlEvents_OnCompleteEvent e) {
            if ((this.OnComplete != null)) {
                this.OnComplete(sender, e);
            }
        }
    }
    
    public delegate void _IDPFPVerificationControlEvents_OnCompleteEventHandler(object sender, _IDPFPVerificationControlEvents_OnCompleteEvent e);
    
    public class _IDPFPVerificationControlEvents_OnCompleteEvent {
        
        public object pFeatureSet;
        
        public object pStatus;
        
        public _IDPFPVerificationControlEvents_OnCompleteEvent(object pFeatureSet, object pStatus) {
            this.pFeatureSet = pFeatureSet;
            this.pStatus = pStatus;
        }
    }
    
    [System.Runtime.InteropServices.ClassInterface(System.Runtime.InteropServices.ClassInterfaceType.None)]
    public class AxDPFPVerificationControlEventMulticaster : DPFPCtlXLib._IDPFPVerificationControlEvents {
        
        private AxDPFPVerificationControl parent;
        
        public AxDPFPVerificationControlEventMulticaster(AxDPFPVerificationControl parent) {
            this.parent = parent;
        }
        
        public virtual void OnComplete(object pFeatureSet, object pStatus) {
            _IDPFPVerificationControlEvents_OnCompleteEvent oncompleteEvent = new _IDPFPVerificationControlEvents_OnCompleteEvent(pFeatureSet, pStatus);
            this.parent.RaiseOnOnComplete(this.parent, oncompleteEvent);
        }
    }
    
    [System.Windows.Forms.AxHost.ClsidAttribute("{0b4409ef-fd2b-4680-9519-d18c528b265e}")]
    [System.ComponentModel.DesignTimeVisibleAttribute(true)]
    [System.ComponentModel.DefaultEvent("OnDelete")]
    public class AxDPFPEnrollmentControl : System.Windows.Forms.AxHost {
        
        private DPFPCtlXLib.IDPFPEnrollmentControl ocx;
        
        private AxDPFPEnrollmentControlEventMulticaster eventMulticaster;
        
        private System.Windows.Forms.AxHost.ConnectionPointCookie cookie;
        
        public AxDPFPEnrollmentControl() : 
                base("0b4409ef-fd2b-4680-9519-d18c528b265e") {
        }
        
        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        [System.Runtime.InteropServices.DispIdAttribute(1)]
        public virtual int MaxEnrollFingerCount {
            get {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("MaxEnrollFingerCount", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertyGet);
                }
                return this.ocx.MaxEnrollFingerCount;
            }
            set {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("MaxEnrollFingerCount", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertySet);
                }
                this.ocx.MaxEnrollFingerCount = value;
            }
        }
        
        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        [System.Runtime.InteropServices.DispIdAttribute(2)]
        public virtual int EnrolledFingersMask {
            get {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("EnrolledFingersMask", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertyGet);
                }
                return this.ocx.EnrolledFingersMask;
            }
            set {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("EnrolledFingersMask", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertySet);
                }
                this.ocx.EnrolledFingersMask = value;
            }
        }
        
        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        [System.Runtime.InteropServices.DispIdAttribute(3)]
        public virtual string ReaderSerialNumber {
            get {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("ReaderSerialNumber", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertyGet);
                }
                return this.ocx.ReaderSerialNumber;
            }
            set {
                if ((this.ocx == null)) {
                    throw new System.Windows.Forms.AxHost.InvalidActiveXStateException("ReaderSerialNumber", System.Windows.Forms.AxHost.ActiveXInvokeKind.PropertySet);
                }
                this.ocx.ReaderSerialNumber = value;
            }
        }
        
        public event _IDPFPEnrollmentControlEvents_OnDeleteEventHandler OnDelete;
        
        public event _IDPFPEnrollmentControlEvents_OnEnrollEventHandler OnEnroll;
        
        public event _IDPFPEnrollmentControlEvents_OnFingerTouchEventHandler OnFingerTouch;
        
        public event _IDPFPEnrollmentControlEvents_OnFingerRemoveEventHandler OnFingerRemove;
        
        public event _IDPFPEnrollmentControlEvents_OnCompleteEventHandler OnComplete;
        
        public event _IDPFPEnrollmentControlEvents_OnReaderConnectEventHandler OnReaderConnect;
        
        public event _IDPFPEnrollmentControlEvents_OnReaderDisconnectEventHandler OnReaderDisconnect;
        
        public event _IDPFPEnrollmentControlEvents_OnSampleQualityEventHandler OnSampleQuality;
        
        public event _IDPFPEnrollmentControlEvents_OnStartEnrollEventHandler OnStartEnroll;
        
        public event _IDPFPEnrollmentControlEvents_OnCancelEnrollEventHandler OnCancelEnroll;
        
        protected override void CreateSink() {
            try {
                this.eventMulticaster = new AxDPFPEnrollmentControlEventMulticaster(this);
                this.cookie = new System.Windows.Forms.AxHost.ConnectionPointCookie(this.ocx, this.eventMulticaster, typeof(DPFPCtlXLib._IDPFPEnrollmentControlEvents));
            }
            catch (System.Exception ) {
            }
        }
        
        protected override void DetachSink() {
            try {
                this.cookie.Disconnect();
            }
            catch (System.Exception ) {
            }
        }
        
        protected override void AttachInterfaces() {
            try {
                this.ocx = ((DPFPCtlXLib.IDPFPEnrollmentControl)(this.GetOcx()));
            }
            catch (System.Exception ) {
            }
        }
        
        internal void RaiseOnOnDelete(object sender, _IDPFPEnrollmentControlEvents_OnDeleteEvent e) {
            if ((this.OnDelete != null)) {
                this.OnDelete(sender, e);
            }
        }
        
        internal void RaiseOnOnEnroll(object sender, _IDPFPEnrollmentControlEvents_OnEnrollEvent e) {
            if ((this.OnEnroll != null)) {
                this.OnEnroll(sender, e);
            }
        }
        
        internal void RaiseOnOnFingerTouch(object sender, _IDPFPEnrollmentControlEvents_OnFingerTouchEvent e) {
            if ((this.OnFingerTouch != null)) {
                this.OnFingerTouch(sender, e);
            }
        }
        
        internal void RaiseOnOnFingerRemove(object sender, _IDPFPEnrollmentControlEvents_OnFingerRemoveEvent e) {
            if ((this.OnFingerRemove != null)) {
                this.OnFingerRemove(sender, e);
            }
        }
        
        internal void RaiseOnOnComplete(object sender, _IDPFPEnrollmentControlEvents_OnCompleteEvent e) {
            if ((this.OnComplete != null)) {
                this.OnComplete(sender, e);
            }
        }
        
        internal void RaiseOnOnReaderConnect(object sender, _IDPFPEnrollmentControlEvents_OnReaderConnectEvent e) {
            if ((this.OnReaderConnect != null)) {
                this.OnReaderConnect(sender, e);
            }
        }
        
        internal void RaiseOnOnReaderDisconnect(object sender, _IDPFPEnrollmentControlEvents_OnReaderDisconnectEvent e) {
            if ((this.OnReaderDisconnect != null)) {
                this.OnReaderDisconnect(sender, e);
            }
        }
        
        internal void RaiseOnOnSampleQuality(object sender, _IDPFPEnrollmentControlEvents_OnSampleQualityEvent e) {
            if ((this.OnSampleQuality != null)) {
                this.OnSampleQuality(sender, e);
            }
        }
        
        internal void RaiseOnOnStartEnroll(object sender, _IDPFPEnrollmentControlEvents_OnStartEnrollEvent e) {
            if ((this.OnStartEnroll != null)) {
                this.OnStartEnroll(sender, e);
            }
        }
        
        internal void RaiseOnOnCancelEnroll(object sender, _IDPFPEnrollmentControlEvents_OnCancelEnrollEvent e) {
            if ((this.OnCancelEnroll != null)) {
                this.OnCancelEnroll(sender, e);
            }
        }
    }
    
    public delegate void _IDPFPEnrollmentControlEvents_OnDeleteEventHandler(object sender, _IDPFPEnrollmentControlEvents_OnDeleteEvent e);
    
    public class _IDPFPEnrollmentControlEvents_OnDeleteEvent {
        
        public int lFingerMask;
        
        public object pStatus;
        
        public _IDPFPEnrollmentControlEvents_OnDeleteEvent(int lFingerMask, object pStatus) {
            this.lFingerMask = lFingerMask;
            this.pStatus = pStatus;
        }
    }
    
    public delegate void _IDPFPEnrollmentControlEvents_OnEnrollEventHandler(object sender, _IDPFPEnrollmentControlEvents_OnEnrollEvent e);
    
    public class _IDPFPEnrollmentControlEvents_OnEnrollEvent {
        
        public int lFingerMask;
        
        public object pTemplate;
        
        public object pStatus;
        
        public _IDPFPEnrollmentControlEvents_OnEnrollEvent(int lFingerMask, object pTemplate, object pStatus) {
            this.lFingerMask = lFingerMask;
            this.pTemplate = pTemplate;
            this.pStatus = pStatus;
        }
    }
    
    public delegate void _IDPFPEnrollmentControlEvents_OnFingerTouchEventHandler(object sender, _IDPFPEnrollmentControlEvents_OnFingerTouchEvent e);
    
    public class _IDPFPEnrollmentControlEvents_OnFingerTouchEvent {
        
        public string pSerialNumber;
        
        public int lEnrolledFinger;
        
        public _IDPFPEnrollmentControlEvents_OnFingerTouchEvent(string pSerialNumber, int lEnrolledFinger) {
            this.pSerialNumber = pSerialNumber;
            this.lEnrolledFinger = lEnrolledFinger;
        }
    }
    
    public delegate void _IDPFPEnrollmentControlEvents_OnFingerRemoveEventHandler(object sender, _IDPFPEnrollmentControlEvents_OnFingerRemoveEvent e);
    
    public class _IDPFPEnrollmentControlEvents_OnFingerRemoveEvent {
        
        public string pSerialNumber;
        
        public int lEnrolledFinger;
        
        public _IDPFPEnrollmentControlEvents_OnFingerRemoveEvent(string pSerialNumber, int lEnrolledFinger) {
            this.pSerialNumber = pSerialNumber;
            this.lEnrolledFinger = lEnrolledFinger;
        }
    }
    
    public delegate void _IDPFPEnrollmentControlEvents_OnCompleteEventHandler(object sender, _IDPFPEnrollmentControlEvents_OnCompleteEvent e);
    
    public class _IDPFPEnrollmentControlEvents_OnCompleteEvent {
        
        public string pSerialNumber;
        
        public int lEnrolledFinger;
        
        public _IDPFPEnrollmentControlEvents_OnCompleteEvent(string pSerialNumber, int lEnrolledFinger) {
            this.pSerialNumber = pSerialNumber;
            this.lEnrolledFinger = lEnrolledFinger;
        }
    }
    
    public delegate void _IDPFPEnrollmentControlEvents_OnReaderConnectEventHandler(object sender, _IDPFPEnrollmentControlEvents_OnReaderConnectEvent e);
    
    public class _IDPFPEnrollmentControlEvents_OnReaderConnectEvent {
        
        public string pSerialNumber;
        
        public int lEnrolledFinger;
        
        public _IDPFPEnrollmentControlEvents_OnReaderConnectEvent(string pSerialNumber, int lEnrolledFinger) {
            this.pSerialNumber = pSerialNumber;
            this.lEnrolledFinger = lEnrolledFinger;
        }
    }
    
    public delegate void _IDPFPEnrollmentControlEvents_OnReaderDisconnectEventHandler(object sender, _IDPFPEnrollmentControlEvents_OnReaderDisconnectEvent e);
    
    public class _IDPFPEnrollmentControlEvents_OnReaderDisconnectEvent {
        
        public string pSerialNumber;
        
        public int lEnrolledFinger;
        
        public _IDPFPEnrollmentControlEvents_OnReaderDisconnectEvent(string pSerialNumber, int lEnrolledFinger) {
            this.pSerialNumber = pSerialNumber;
            this.lEnrolledFinger = lEnrolledFinger;
        }
    }
    
    public delegate void _IDPFPEnrollmentControlEvents_OnSampleQualityEventHandler(object sender, _IDPFPEnrollmentControlEvents_OnSampleQualityEvent e);
    
    public class _IDPFPEnrollmentControlEvents_OnSampleQualityEvent {
        
        public string pSerialNumber;
        
        public int lEnrolledFinger;
        
        public int lSampleQuality;
        
        public _IDPFPEnrollmentControlEvents_OnSampleQualityEvent(string pSerialNumber, int lEnrolledFinger, int lSampleQuality) {
            this.pSerialNumber = pSerialNumber;
            this.lEnrolledFinger = lEnrolledFinger;
            this.lSampleQuality = lSampleQuality;
        }
    }
    
    public delegate void _IDPFPEnrollmentControlEvents_OnStartEnrollEventHandler(object sender, _IDPFPEnrollmentControlEvents_OnStartEnrollEvent e);
    
    public class _IDPFPEnrollmentControlEvents_OnStartEnrollEvent {
        
        public string pSerialNumber;
        
        public int lEnrolledFinger;
        
        public _IDPFPEnrollmentControlEvents_OnStartEnrollEvent(string pSerialNumber, int lEnrolledFinger) {
            this.pSerialNumber = pSerialNumber;
            this.lEnrolledFinger = lEnrolledFinger;
        }
    }
    
    public delegate void _IDPFPEnrollmentControlEvents_OnCancelEnrollEventHandler(object sender, _IDPFPEnrollmentControlEvents_OnCancelEnrollEvent e);
    
    public class _IDPFPEnrollmentControlEvents_OnCancelEnrollEvent {
        
        public string pSerialNumber;
        
        public int lEnrolledFinger;
        
        public _IDPFPEnrollmentControlEvents_OnCancelEnrollEvent(string pSerialNumber, int lEnrolledFinger) {
            this.pSerialNumber = pSerialNumber;
            this.lEnrolledFinger = lEnrolledFinger;
        }
    }
    
    [System.Runtime.InteropServices.ClassInterface(System.Runtime.InteropServices.ClassInterfaceType.None)]
    public class AxDPFPEnrollmentControlEventMulticaster : DPFPCtlXLib._IDPFPEnrollmentControlEvents {
        
        private AxDPFPEnrollmentControl parent;
        
        public AxDPFPEnrollmentControlEventMulticaster(AxDPFPEnrollmentControl parent) {
            this.parent = parent;
        }
        
        public virtual void OnDelete(int lFingerMask, object pStatus) {
            _IDPFPEnrollmentControlEvents_OnDeleteEvent ondeleteEvent = new _IDPFPEnrollmentControlEvents_OnDeleteEvent(lFingerMask, pStatus);
            this.parent.RaiseOnOnDelete(this.parent, ondeleteEvent);
        }
        
        public virtual void OnEnroll(int lFingerMask, object pTemplate, object pStatus) {
            _IDPFPEnrollmentControlEvents_OnEnrollEvent onenrollEvent = new _IDPFPEnrollmentControlEvents_OnEnrollEvent(lFingerMask, pTemplate, pStatus);
            this.parent.RaiseOnOnEnroll(this.parent, onenrollEvent);
        }
        
        public virtual void OnFingerTouch(string pSerialNumber, int lEnrolledFinger) {
            _IDPFPEnrollmentControlEvents_OnFingerTouchEvent onfingertouchEvent = new _IDPFPEnrollmentControlEvents_OnFingerTouchEvent(pSerialNumber, lEnrolledFinger);
            this.parent.RaiseOnOnFingerTouch(this.parent, onfingertouchEvent);
        }
        
        public virtual void OnFingerRemove(string pSerialNumber, int lEnrolledFinger) {
            _IDPFPEnrollmentControlEvents_OnFingerRemoveEvent onfingerremoveEvent = new _IDPFPEnrollmentControlEvents_OnFingerRemoveEvent(pSerialNumber, lEnrolledFinger);
            this.parent.RaiseOnOnFingerRemove(this.parent, onfingerremoveEvent);
        }
        
        public virtual void OnComplete(string pSerialNumber, int lEnrolledFinger) {
            _IDPFPEnrollmentControlEvents_OnCompleteEvent oncompleteEvent = new _IDPFPEnrollmentControlEvents_OnCompleteEvent(pSerialNumber, lEnrolledFinger);
            this.parent.RaiseOnOnComplete(this.parent, oncompleteEvent);
        }
        
        public virtual void OnReaderConnect(string pSerialNumber, int lEnrolledFinger) {
            _IDPFPEnrollmentControlEvents_OnReaderConnectEvent onreaderconnectEvent = new _IDPFPEnrollmentControlEvents_OnReaderConnectEvent(pSerialNumber, lEnrolledFinger);
            this.parent.RaiseOnOnReaderConnect(this.parent, onreaderconnectEvent);
        }
        
        public virtual void OnReaderDisconnect(string pSerialNumber, int lEnrolledFinger) {
            _IDPFPEnrollmentControlEvents_OnReaderDisconnectEvent onreaderdisconnectEvent = new _IDPFPEnrollmentControlEvents_OnReaderDisconnectEvent(pSerialNumber, lEnrolledFinger);
            this.parent.RaiseOnOnReaderDisconnect(this.parent, onreaderdisconnectEvent);
        }
        
        public virtual void OnSampleQuality(string pSerialNumber, int lEnrolledFinger, int lSampleQuality) {
            _IDPFPEnrollmentControlEvents_OnSampleQualityEvent onsamplequalityEvent = new _IDPFPEnrollmentControlEvents_OnSampleQualityEvent(pSerialNumber, lEnrolledFinger, lSampleQuality);
            this.parent.RaiseOnOnSampleQuality(this.parent, onsamplequalityEvent);
        }
        
        public virtual void OnStartEnroll(string pSerialNumber, int lEnrolledFinger) {
            _IDPFPEnrollmentControlEvents_OnStartEnrollEvent onstartenrollEvent = new _IDPFPEnrollmentControlEvents_OnStartEnrollEvent(pSerialNumber, lEnrolledFinger);
            this.parent.RaiseOnOnStartEnroll(this.parent, onstartenrollEvent);
        }
        
        public virtual void OnCancelEnroll(string pSerialNumber, int lEnrolledFinger) {
            _IDPFPEnrollmentControlEvents_OnCancelEnrollEvent oncancelenrollEvent = new _IDPFPEnrollmentControlEvents_OnCancelEnrollEvent(pSerialNumber, lEnrolledFinger);
            this.parent.RaiseOnOnCancelEnroll(this.parent, oncancelenrollEvent);
        }
    }
}
